name: SwiftLint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
