name: Build Xcode Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Xcode Project
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: CodingChallenge.xcodeproj
          scheme: CodingChallenge
          sdk: iphonesimulator
          action: build-for-testing
