name: Build Xcode Project
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Xcode Project
        uses: apple-actions/xcode@v3
        with:
          actions: build-for-testing
          scheme: MyScheme
          sdk: iphonesimulator
