name: Test Xcode Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Xcode Project
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: CodingChallenge.xcodeproj
          scheme: CodingChallenge
          sdk: iphonesimulator
          action: build-for-testing
      - name: Test Xcode Project
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: CodingChallenge.xcodeproj
          scheme: CodingChallenge
          sdk: iphonesimulator
          action: test-without-building
