name: Build Xcode Project
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      scheme:
        required: true
        type: string
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Xcode Project
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: ${{ inputs.project }}
          scheme: ${{ inputs.scheme }}
          sdk: iphonesimulator
          action: build-for-testing
